version: "3.8"
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"   # mapeamos puerto 80 del contenedor (nginx) a 5173 local
    restart: unless-stopped
